"""PDF Template ORM model."""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import JSON, Boolean, ForeignKey, LargeBinary, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.models.base import Base, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from backend.app.models.user import User


class PDFTemplate(UUIDMixin, TimestampMixin, Base):
    """Reusable PDF template with branding and layout settings.

    Stores logo, company name, colours, header/footer text and
    optionally a base PDF file that panels are overlaid onto.
    """

    __tablename__ = "pdf_templates"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_default: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # --- Branding ---
    company_name: Mapped[str] = mapped_column(String(255), default="", nullable=False)
    logo_base64: Mapped[str | None] = mapped_column(Text, nullable=True)
    logo_mime_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    primary_color: Mapped[str] = mapped_column(String(20), default="#2196F3", nullable=False)
    secondary_color: Mapped[str] = mapped_column(String(20), default="#1a1a1a", nullable=False)

    # --- Header / Footer ---
    header_text: Mapped[str] = mapped_column(String(500), default="", nullable=False)
    footer_text: Mapped[str] = mapped_column(
        String(500),
        default="Generated by Grafana PDF Reporter",
        nullable=False,
    )
    show_date: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    show_page_numbers: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # --- Imported base PDF (optional) ---
    base_pdf_data: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    base_pdf_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # --- Layout config stored as JSON ---
    layout_config: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # --- Ownership ---
    created_by_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id"),
        nullable=False,
    )

    created_by: Mapped[User] = relationship(back_populates="pdf_templates")
