"""PDF rendering engine using Jinja2 and WeasyPrint."""

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal, cast

from jinja2 import Environment, FileSystemLoader, TemplateNotFound
from weasyprint import HTML

from backend.app.core.exceptions import PDFRenderError
from backend.app.core.i18n import DEFAULT_LOCALE, get_translations

logger = logging.getLogger(__name__)


@dataclass
class PanelImage:
    """Represents a rendered panel image for PDF inclusion.

    Attributes:
        panel_id: Grafana panel ID.
        title: Panel display title.
        image_base64: Base64-encoded PNG image data.
    """

    panel_id: int
    title: str
    image_base64: str


@dataclass
class DataTableColumn:
    """A column definition for a data table.

    Attributes:
        header: Column header text.
        values: List of string values for each row.
    """

    header: str
    values: list[str] = field(default_factory=list)


@dataclass
class DataTable:
    """Tabular data to include as annex in the PDF.

    Attributes:
        panel_id: Grafana panel ID the data belongs to.
        title: Table display title.
        columns: List of column definitions.
    """

    panel_id: int
    title: str
    columns: list[DataTableColumn] = field(default_factory=list)

    @property
    def row_count(self) -> int:
        """Return the number of data rows."""
        if not self.columns:
            return 0
        return len(self.columns[0].values)


@dataclass
class ComparisonPanel:
    """A pair of panel images for temporal comparison.

    Attributes:
        panel_id: Grafana panel ID.
        title: Panel display title.
        image_a_base64: Base64-encoded PNG for period A.
        image_b_base64: Base64-encoded PNG for period B.
    """

    panel_id: int
    title: str
    image_a_base64: str
    image_b_base64: str


@dataclass
class ReportContext:
    """All data needed to render a PDF report.

    Attributes:
        report_title: Main title displayed on the report.
        dashboard_title: Grafana dashboard title.
        dashboard_uid: Grafana dashboard UID.
        generated_at: ISO formatted generation timestamp.
        time_range_from: Time range start (Grafana format).
        time_range_to: Time range end (Grafana format).
        panels: List of panel images to include.
        description: Optional report description.
        company_name: Company name displayed in header/footer.
    """

    report_title: str
    dashboard_title: str
    dashboard_uid: str
    generated_at: str
    time_range_from: str
    time_range_to: str
    panels: list[PanelImage] = field(default_factory=list)
    description: str | None = None
    company_name: str = "SOME S.A.U."

    # Template branding fields
    logo_base64: str | None = None
    logo_mime_type: str | None = None
    primary_color: str = "#2196F3"
    secondary_color: str = "#1a1a1a"
    header_text: str = ""
    footer_text: str = "Generated by Grafana PDF Reporter"
    show_date: bool = True
    show_page_numbers: bool = True

    # Locale for PDF labels
    locale: str = DEFAULT_LOCALE

    # --- Sprint 5: PDF Engine Enhancements ---

    # Page orientation: portrait (default) or landscape
    orientation: Literal["portrait", "landscape"] = "portrait"

    # Table of Contents: auto-generate TOC page with panel links
    toc_enabled: bool = False

    # Watermark: text overlay on every page (e.g. "Confidential", "Draft")
    watermark_text: str | None = None

    # Panel grid columns (1 = full width, 2 = two columns side by side)
    panel_columns: int = 1

    # Data tables: raw panel data as table annex
    data_tables: list[DataTable] = field(default_factory=list)

    # Temporal comparison panels
    comparison_panels: list[ComparisonPanel] = field(default_factory=list)
    comparison_time_from_a: str | None = None
    comparison_time_to_a: str | None = None
    comparison_time_from_b: str | None = None
    comparison_time_to_b: str | None = None


class PDFEngine:
    """Renders HTML templates to PDF using Jinja2 and WeasyPrint.

    The engine loads Jinja2 templates from the templates directory,
    injects report data, and converts the resulting HTML to PDF bytes.

    Args:
        template_dir: Absolute path to the templates/ directory.
    """

    def __init__(self, template_dir: str | Path) -> None:
        self._template_dir = Path(template_dir)
        self._env = Environment(
            loader=FileSystemLoader(str(self._template_dir)),
            autoescape=True,
        )

    def render_report(self, context: ReportContext) -> bytes:
        """Render a complete PDF report from the given context.

        Args:
            context: All data needed for the report template.

        Returns:
            Raw PDF bytes.

        Raises:
            PDFRenderError: If template rendering or PDF conversion fails.
        """
        logger.info(
            "Rendering PDF for '%s' (%d panels)",
            context.report_title,
            len(context.panels),
        )

        # Inject i18n labels based on locale
        tr = get_translations(context.locale)

        template_vars = {
            "report_title": context.report_title,
            "dashboard_title": context.dashboard_title,
            "dashboard_uid": context.dashboard_uid,
            "generated_at": context.generated_at,
            "time_range_from": context.time_range_from,
            "time_range_to": context.time_range_to,
            "panels": context.panels,
            "description": context.description,
            "company_name": context.company_name,
            "logo_base64": context.logo_base64,
            "logo_mime_type": context.logo_mime_type,
            "primary_color": context.primary_color,
            "secondary_color": context.secondary_color,
            "header_text": context.header_text,
            "footer_text": context.footer_text,
            "show_date": context.show_date,
            "show_page_numbers": context.show_page_numbers,
            "locale": context.locale,
            # i18n labels for the template
            "i18n_dashboard_label": tr["pdf.dashboard_label"],
            "i18n_dashboard_uid": tr["pdf.dashboard_uid"],
            "i18n_generated_at": tr["pdf.generated_at"],
            "i18n_time_range": tr["pdf.time_range"],
            "i18n_panels_included": tr["pdf.panels_included"],
            "i18n_panels_section": tr["pdf.panels_section"],
            "i18n_image_not_available": tr["pdf.image_not_available"],
            "i18n_page": tr["pdf.page"],
            # Sprint 5: PDF engine enhancement variables
            "orientation": context.orientation,
            "toc_enabled": context.toc_enabled,
            "watermark_text": context.watermark_text,
            "panel_columns": context.panel_columns,
            "data_tables": context.data_tables,
            "comparison_panels": context.comparison_panels,
            "comparison_time_from_a": context.comparison_time_from_a,
            "comparison_time_to_a": context.comparison_time_to_a,
            "comparison_time_from_b": context.comparison_time_from_b,
            "comparison_time_to_b": context.comparison_time_to_b,
            # i18n labels for enhancements
            "i18n_toc_title": tr["pdf.toc_title"],
            "i18n_toc_panel": tr["pdf.toc_panel"],
            "i18n_data_tables_section": tr["pdf.data_tables_section"],
            "i18n_data_table_no_data": tr["pdf.data_table_no_data"],
            "i18n_comparison_title": tr["pdf.comparison_title"],
            "i18n_comparison_period_a": tr["pdf.comparison_period_a"],
            "i18n_comparison_period_b": tr["pdf.comparison_period_b"],
        }

        html_content = self._render_html("report.html", template_vars)
        pdf_bytes = self._html_to_pdf(html_content)

        # Apply watermark overlay if requested
        if context.watermark_text:
            pdf_bytes = self._apply_watermark(pdf_bytes, context.watermark_text)

        logger.info("PDF rendered successfully (%d bytes)", len(pdf_bytes))
        return pdf_bytes

    def _render_html(self, template_name: str, context: dict[str, Any]) -> str:
        """Render a Jinja2 template to an HTML string.

        Args:
            template_name: Name of the template file (e.g. 'report.html').
            context: Template variable dict.

        Returns:
            Rendered HTML string.

        Raises:
            PDFRenderError: If template is not found or rendering fails.
        """
        try:
            template = self._env.get_template(template_name)
            return template.render(**context)
        except TemplateNotFound as e:
            raise PDFRenderError(f"Template '{template_name}' not found") from e
        except Exception as e:
            raise PDFRenderError(f"Template rendering error: {e}") from e

    def _html_to_pdf(self, html_content: str) -> bytes:
        """Convert an HTML string to PDF bytes using WeasyPrint.

        Args:
            html_content: Complete HTML document string.

        Returns:
            Raw PDF file bytes.

        Raises:
            PDFRenderError: If WeasyPrint conversion fails.
        """
        try:
            html = HTML(
                string=html_content,
                base_url=str(self._template_dir),
            )
            return cast(bytes, html.write_pdf())
        except Exception as e:
            raise PDFRenderError(f"WeasyPrint conversion error: {e}") from e

    def _apply_watermark(self, pdf_bytes: bytes, watermark_text: str) -> bytes:
        """Apply a diagonal text watermark to every page of the PDF.

        Creates a transparent watermark page using WeasyPrint, then merges
        it onto each page of the source PDF using pypdf.

        Args:
            pdf_bytes: Original PDF bytes.
            watermark_text: Text to display as watermark.

        Returns:
            PDF bytes with watermark applied.

        Raises:
            PDFRenderError: If watermark application fails.
        """
        import io

        from pypdf import PdfReader, PdfWriter

        try:
            # Generate a single-page watermark PDF via WeasyPrint
            watermark_html = f"""
            <html><body style="margin:0;padding:0;">
            <div style="
                position: fixed;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%) rotate(-45deg);
                font-size: 72px;
                color: rgba(200, 200, 200, 0.3);
                font-family: Arial, sans-serif;
                font-weight: bold;
                white-space: nowrap;
                pointer-events: none;
                z-index: 9999;
            ">{watermark_text}</div>
            </body></html>
            """
            watermark_pdf = HTML(string=watermark_html).write_pdf()

            source_reader = PdfReader(io.BytesIO(pdf_bytes))
            watermark_reader = PdfReader(io.BytesIO(watermark_pdf))
            watermark_page = watermark_reader.pages[0]
            writer = PdfWriter()

            for page in source_reader.pages:
                page.merge_page(watermark_page)
                writer.add_page(page)

            output = io.BytesIO()
            writer.write(output)
            logger.info("Watermark '%s' applied to %d pages", watermark_text, len(writer.pages))
            return output.getvalue()
        except Exception as e:
            raise PDFRenderError(f"Watermark application error: {e}") from e

    def overlay_on_base_pdf(self, base_pdf_bytes: bytes, content_pdf_bytes: bytes) -> bytes:
        """Overlay generated report pages onto a base PDF template.

        Each page of the content PDF is merged on top of the
        corresponding page of the base PDF. If the content has more
        pages than the base, extra pages use the *last* base page as
        background (useful for letterhead templates).

        Args:
            base_pdf_bytes: Raw bytes of the base/template PDF.
            content_pdf_bytes: Raw bytes of the generated report PDF.

        Returns:
            Merged PDF bytes.

        Raises:
            PDFRenderError: If merge fails.
        """
        import io

        from pypdf import PdfReader, PdfWriter

        try:
            base_reader = PdfReader(io.BytesIO(base_pdf_bytes))
            content_reader = PdfReader(io.BytesIO(content_pdf_bytes))
            writer = PdfWriter()

            for i, content_page in enumerate(content_reader.pages):
                # Use corresponding base page, or last base page as fallback
                base_idx = min(i, len(base_reader.pages) - 1)
                base_page = base_reader.pages[base_idx]

                # Clone the base page and merge content on top
                import copy

                merged_page = copy.copy(base_page)
                merged_page.merge_page(content_page)
                writer.add_page(merged_page)

            output = io.BytesIO()
            writer.write(output)
            logger.info("PDF overlay complete: %d pages", len(writer.pages))
            return output.getvalue()
        except Exception as e:
            raise PDFRenderError(f"PDF overlay error: {e}") from e
