apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-reporter.fullname" . }}-secret
  labels:
    {{- include "grafana-reporter.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.env.POSTGRES_PASSWORD | default "changeme" | b64enc | quote }}
  jwt-secret-key: {{ .Values.env.JWT_SECRET_KEY | default "change-me" | b64enc | quote }}
