"""add_pdf_templates_table

Revision ID: 14409ba5b427
Revises: 776166b7436c
Create Date: 2026-02-24 14:57:03.257548
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14409ba5b427'
down_revision: str | None = '776166b7436c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('logo_base64', sa.Text(), nullable=True),
    sa.Column('logo_mime_type', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('secondary_color', sa.String(length=20), nullable=False),
    sa.Column('header_text', sa.String(length=500), nullable=False),
    sa.Column('footer_text', sa.String(length=500), nullable=False),
    sa.Column('show_date', sa.Boolean(), nullable=False),
    sa.Column('show_page_numbers', sa.Boolean(), nullable=False),
    sa.Column('base_pdf_data', sa.LargeBinary(), nullable=True),
    sa.Column('base_pdf_name', sa.String(length=255), nullable=True),
    sa.Column('layout_config', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_templates')
    # ### end Alembic commands ###
