"""PDF Template request and response schemas."""

import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class TemplateCreateRequest(BaseModel):
    """Schema for creating or updating a PDF template.

    Attributes:
        name: Template display name.
        description: Optional description.
        company_name: Company / brand name for header.
        logo_base64: Base64-encoded logo image data.
        logo_mime_type: MIME type of the logo (image/png, image/jpeg).
        primary_color: Primary accent colour (hex).
        secondary_color: Secondary colour (hex).
        header_text: Custom header text.
        footer_text: Custom footer text.
        show_date: Whether to show date on report.
        show_page_numbers: Whether to show page numbers.
        is_default: Mark as user's default template.
        layout_config: Optional JSON layout configuration.
    """

    name: str = Field(..., min_length=1, max_length=255)
    description: str | None = None
    company_name: str = Field(default="", max_length=255)
    logo_base64: str | None = None
    logo_mime_type: str | None = Field(default=None, pattern=r"^image/(png|jpeg|svg\+xml)$")
    primary_color: str = Field(default="#2196F3", pattern=r"^#[0-9a-fA-F]{6}$")
    secondary_color: str = Field(default="#1a1a1a", pattern=r"^#[0-9a-fA-F]{6}$")
    header_text: str = Field(default="", max_length=500)
    footer_text: str = Field(default="Generated by Grafana PDF Reporter", max_length=500)
    show_date: bool = True
    show_page_numbers: bool = True
    is_default: bool = False
    layout_config: dict | None = None


class TemplateUploadPDFRequest(BaseModel):
    """Schema for uploading a base PDF to a template.

    Attributes:
        base_pdf_base64: Base64-encoded PDF file data.
        base_pdf_name: Original filename.
    """

    base_pdf_base64: str
    base_pdf_name: str = Field(..., max_length=255)


class TemplateResponse(BaseModel):
    """Schema for template metadata responses.

    Attributes:
        id: Template UUID.
        name: Template name.
        description: Optional description.
        company_name: Company name.
        has_logo: Whether a logo is set.
        logo_mime_type: Logo MIME type if set.
        primary_color: Primary colour.
        secondary_color: Secondary colour.
        header_text: Header text.
        footer_text: Footer text.
        show_date: Show date flag.
        show_page_numbers: Show page numbers flag.
        is_default: Default template flag.
        has_base_pdf: Whether a base PDF is uploaded.
        base_pdf_name: Base PDF filename if set.
        layout_config: Layout configuration.
        created_by_id: Owner user UUID.
        created_at: Creation timestamp.
        updated_at: Last update timestamp.
    """

    id: uuid.UUID
    name: str
    description: str | None
    company_name: str
    has_logo: bool
    logo_mime_type: str | None
    primary_color: str
    secondary_color: str
    header_text: str
    footer_text: str
    show_date: bool
    show_page_numbers: bool
    is_default: bool
    has_base_pdf: bool
    base_pdf_name: str | None
    layout_config: dict | None
    created_by_id: uuid.UUID
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)

    @classmethod
    def from_model(cls, template: object) -> "TemplateResponse":
        """Build response from ORM model, computing has_logo and has_base_pdf."""
        from backend.app.models.pdf_template import PDFTemplate

        t: PDFTemplate = template  # type: ignore[assignment]
        return cls(
            id=t.id,
            name=t.name,
            description=t.description,
            company_name=t.company_name,
            has_logo=bool(t.logo_base64),
            logo_mime_type=t.logo_mime_type,
            primary_color=t.primary_color,
            secondary_color=t.secondary_color,
            header_text=t.header_text,
            footer_text=t.footer_text,
            show_date=t.show_date,
            show_page_numbers=t.show_page_numbers,
            is_default=t.is_default,
            has_base_pdf=bool(t.base_pdf_data),
            base_pdf_name=t.base_pdf_name,
            layout_config=t.layout_config,
            created_by_id=t.created_by_id,
            created_at=t.created_at,
            updated_at=t.updated_at,
        )
