import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import {
  getTemplatesAPI,
  createTemplateAPI,
  updateTemplateAPI,
  deleteTemplateAPI,
  uploadTemplatePDFFileAPI,
  removeTemplatePDFAPI,
} from '../api/client'
import { useLanguage } from '../context/LanguageContext'

const DEFAULT_TEMPLATE = {
  name: '',
  description: '',
  company_name: '',
  logo_base64: null,
  logo_mime_type: null,
  primary_color: '#2196F3',
  secondary_color: '#1a1a1a',
  header_text: '',
  footer_text: 'Generated by Grafana PDF Reporter',
  show_date: true,
  show_page_numbers: true,
  is_default: false,
}

export default function TemplatesPage() {
  const { t } = useLanguage()
  const [templates, setTemplates] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [editing, setEditing] = useState(null)
  const [saving, setSaving] = useState(false)
  const [pendingPDFFile, setPendingPDFFile] = useState(null)

  useEffect(() => {
    loadTemplates()
  }, [])

  const loadTemplates = async () => {
    try {
      setLoading(true)
      const res = await getTemplatesAPI()
      setTemplates(res.data)
    } catch (err) {
      setError(err.response?.data?.detail || t('templates.error_load'))
    } finally {
      setLoading(false)
    }
  }

  const handleNew = () => {
    setEditing({ ...DEFAULT_TEMPLATE, _isNew: true })
    setError(null)
  }

  const handleEdit = (tpl) => {
    setEditing({ ...tpl, _isNew: false })
    setError(null)
  }

  const handleDelete = async (id) => {
    if (!confirm(t('templates.confirm_delete'))) return
    try {
      await deleteTemplateAPI(id)
      setTemplates((prev) => prev.filter((tpl) => tpl.id !== id))
    } catch (err) {
      setError(err.response?.data?.detail || t('templates.error_delete'))
    }
  }

  const handleSave = async () => {
    setSaving(true)
    setError(null)
    try {
      const data = { ...editing }
      const isNew = data._isNew
      delete data._isNew
      delete data.id
      delete data.has_logo
      delete data.has_base_pdf
      delete data.base_pdf_name
      delete data.created_by_id
      delete data.created_at
      delete data.updated_at
      delete data.layout_config

      let savedId = editing.id
      if (isNew) {
        const res = await createTemplateAPI(data)
        savedId = res.data.id
      } else {
        await updateTemplateAPI(editing.id, data)
      }

      if (pendingPDFFile && savedId) {
        try {
          await uploadTemplatePDFFileAPI(savedId, pendingPDFFile)
        } catch (err) {
          setError(err.response?.data?.detail || t('templates.error_pdf_save'))
        }
        setPendingPDFFile(null)
      }

      setEditing(null)
      await loadTemplates()
    } catch (err) {
      setError(err.response?.data?.detail || t('templates.error_save'))
    } finally {
      setSaving(false)
    }
  }

  const handleLogoUpload = (e) => {
    const file = e.target.files[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => {
      const base64 = reader.result.split(',')[1]
      setEditing((prev) => ({
        ...prev,
        logo_base64: base64,
        logo_mime_type: file.type,
      }))
    }
    reader.readAsDataURL(file)
  }

  const handleRemoveLogo = () => {
    setEditing((prev) => ({
      ...prev,
      logo_base64: null,
      logo_mime_type: null,
    }))
  }

  const handlePDFUpload = async (e) => {
    const file = e.target.files[0]
    if (!file || !editing?.id) return
    try {
      await uploadTemplatePDFFileAPI(editing.id, file)
      setEditing((prev) => ({
        ...prev,
        has_base_pdf: true,
        base_pdf_name: file.name,
      }))
    } catch (err) {
      setError(err.response?.data?.detail || t('templates.error_pdf_upload'))
    }
  }

  const handleRemovePDF = async () => {
    if (!editing?.id) return
    try {
      await removeTemplatePDFAPI(editing.id)
      setEditing((prev) => ({
        ...prev,
        has_base_pdf: false,
        base_pdf_name: null,
      }))
    } catch (err) {
      setError(err.response?.data?.detail || t('templates.error_pdf_remove'))
    }
  }

  const setField = (field, value) => {
    setEditing((prev) => ({ ...prev, [field]: value }))
  }

  // ─── EDITOR VIEW ───
  if (editing) {
    return (
      <div className="max-w-4xl mx-auto">
        <button
          onClick={() => setEditing(null)}
          className="text-primary-600 hover:text-primary-800 text-sm font-medium mb-6 inline-flex items-center space-x-1"
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5 8.25 12l7.5-7.5" />
          </svg>
          <span>{t('templates.back')}</span>
        </button>

        <h1 className="text-2xl font-bold text-gray-900 mb-6">
          {editing._isNew ? t('templates.new_title') : t('templates.edit_title')}
        </h1>

        {error && (
          <div className="bg-red-50 text-red-700 px-4 py-3 rounded-lg mb-4">{error}</div>
        )}

        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 space-y-6">
          {/* Basic info */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">{t('templates.name')}</label>
              <input
                type="text"
                value={editing.name}
                onChange={(e) => setField('name', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
                placeholder={t('templates.name_placeholder')}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">{t('templates.company')}</label>
              <input
                type="text"
                value={editing.company_name}
                onChange={(e) => setField('company_name', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
                placeholder={t('templates.company_placeholder')}
              />
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">{t('templates.description')}</label>
            <textarea
              value={editing.description || ''}
              onChange={(e) => setField('description', e.target.value)}
              rows={2}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
              placeholder={t('templates.description_placeholder')}
            />
          </div>

          {/* Logo */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">{t('templates.logo')}</label>
            <div className="flex items-center space-x-4">
              {editing.logo_base64 ? (
                <div className="flex items-center space-x-3">
                  <img
                    src={`data:${editing.logo_mime_type};base64,${editing.logo_base64}`}
                    alt="Logo preview"
                    className="h-12 max-w-[120px] object-contain border border-gray-200 rounded p-1"
                  />
                  <button
                    onClick={handleRemoveLogo}
                    className="text-red-600 hover:text-red-800 text-sm font-medium"
                  >
                    {t('templates.logo_remove')}
                  </button>
                </div>
              ) : (
                <label className="cursor-pointer bg-gray-50 hover:bg-gray-100 border border-dashed border-gray-300 rounded-lg px-4 py-3 text-sm text-gray-600">
                  <input type="file" accept="image/png,image/jpeg,image/svg+xml" onChange={handleLogoUpload} className="hidden" />
                  {t('templates.logo_upload')}
                </label>
              )}
            </div>
          </div>

          {/* Colours */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">{t('templates.primary_color')}</label>
              <div className="flex items-center space-x-2">
                <input
                  type="color"
                  value={editing.primary_color}
                  onChange={(e) => setField('primary_color', e.target.value)}
                  className="w-10 h-10 rounded border border-gray-300 cursor-pointer"
                />
                <input
                  type="text"
                  value={editing.primary_color}
                  onChange={(e) => setField('primary_color', e.target.value)}
                  className="w-28 px-2 py-1 border border-gray-300 rounded text-sm"
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">{t('templates.secondary_color')}</label>
              <div className="flex items-center space-x-2">
                <input
                  type="color"
                  value={editing.secondary_color}
                  onChange={(e) => setField('secondary_color', e.target.value)}
                  className="w-10 h-10 rounded border border-gray-300 cursor-pointer"
                />
                <input
                  type="text"
                  value={editing.secondary_color}
                  onChange={(e) => setField('secondary_color', e.target.value)}
                  className="w-28 px-2 py-1 border border-gray-300 rounded text-sm"
                />
              </div>
            </div>
          </div>

          {/* Header / Footer */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">{t('templates.header_text')}</label>
              <input
                type="text"
                value={editing.header_text}
                onChange={(e) => setField('header_text', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
                placeholder={t('templates.header_placeholder')}
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">{t('templates.footer_text')}</label>
              <input
                type="text"
                value={editing.footer_text}
                onChange={(e) => setField('footer_text', e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none"
                placeholder={t('templates.footer_placeholder')}
              />
            </div>
          </div>

          {/* Toggles */}
          <div className="flex flex-wrap gap-6">
            <label className="flex items-center space-x-2 cursor-pointer">
              <input
                type="checkbox"
                checked={editing.show_date}
                onChange={(e) => setField('show_date', e.target.checked)}
                className="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
              />
              <span className="text-sm text-gray-700">{t('templates.show_date')}</span>
            </label>
            <label className="flex items-center space-x-2 cursor-pointer">
              <input
                type="checkbox"
                checked={editing.show_page_numbers}
                onChange={(e) => setField('show_page_numbers', e.target.checked)}
                className="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
              />
              <span className="text-sm text-gray-700">{t('templates.show_page_numbers')}</span>
            </label>
            <label className="flex items-center space-x-2 cursor-pointer">
              <input
                type="checkbox"
                checked={editing.is_default}
                onChange={(e) => setField('is_default', e.target.checked)}
                className="rounded border-gray-300 text-primary-600 focus:ring-primary-500"
              />
              <span className="text-sm text-gray-700">{t('templates.is_default')}</span>
            </label>
          </div>

          {/* Base PDF Upload */}
          <div className="border-t border-gray-200 pt-4">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t('templates.base_pdf')}
            </label>
            <p className="text-xs text-gray-500 mb-3">
              {t('templates.base_pdf_desc')}
            </p>
            {editing.has_base_pdf || pendingPDFFile ? (
              <div className="flex items-center space-x-3 bg-green-50 p-3 rounded-lg">
                <svg className="w-5 h-5 text-green-600" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                </svg>
                <span className="text-sm text-green-800 font-medium">
                  {pendingPDFFile ? pendingPDFFile.name : editing.base_pdf_name}
                </span>
                <button
                  onClick={() => {
                    if (pendingPDFFile) {
                      setPendingPDFFile(null)
                    } else {
                      handleRemovePDF()
                    }
                  }}
                  className="text-red-600 hover:text-red-800 text-sm font-medium ml-auto"
                >
                  {t('templates.base_pdf_remove')}
                </button>
              </div>
            ) : (
              <label className="cursor-pointer bg-gray-50 hover:bg-gray-100 border border-dashed border-gray-300 rounded-lg px-4 py-3 text-sm text-gray-600 inline-flex items-center space-x-2">
                <svg className="w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5m-13.5-9L12 3m0 0 4.5 4.5M12 3v13.5" />
                </svg>
                <input
                  type="file"
                  accept="application/pdf"
                  onChange={(e) => {
                    const file = e.target.files[0]
                    if (!file) return
                    if (editing._isNew) {
                      setPendingPDFFile(file)
                    } else {
                      handlePDFUpload(e)
                    }
                  }}
                  className="hidden"
                />
                <span>{t('templates.base_pdf_select')}</span>
              </label>
            )}
          </div>

          {/* Preview */}
          <div className="border-t border-gray-200 pt-4">
            <h3 className="text-sm font-medium text-gray-700 mb-3">{t('templates.preview')}</h3>
            <div className="border border-gray-200 rounded-lg p-4 bg-white" style={{ maxWidth: '600px' }}>
              <div style={{ borderBottom: `3px solid ${editing.primary_color}`, paddingBottom: '8px', marginBottom: '12px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    {editing.company_name && (
                      <div style={{ fontSize: '9px', color: '#999', textTransform: 'uppercase', letterSpacing: '1px' }}>
                        {editing.company_name}
                      </div>
                    )}
                    {editing.header_text && (
                      <div style={{ fontSize: '8px', color: '#777' }}>{editing.header_text}</div>
                    )}
                  </div>
                  {editing.logo_base64 && (
                    <img
                      src={`data:${editing.logo_mime_type};base64,${editing.logo_base64}`}
                      alt="Logo"
                      style={{ maxHeight: '30px', maxWidth: '100px' }}
                    />
                  )}
                </div>
                <div style={{ fontSize: '16px', fontWeight: 700, color: editing.secondary_color, marginTop: '4px' }}>
                  {t('templates.preview_title')}
                </div>
                <div style={{ fontSize: '11px', color: '#666' }}>{t('templates.preview_dashboard')}</div>
              </div>
              <div style={{ backgroundColor: '#f0f4f8', padding: '3px 6px', borderLeft: `3px solid ${editing.primary_color}`, fontSize: '10px', fontWeight: 600, color: '#444', marginBottom: '8px' }}>
                {t('templates.preview_panel')}
              </div>
              <div style={{ width: '100%', height: '40px', backgroundColor: '#f5f5f5', border: '1px solid #e0e0e0', borderRadius: '2px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '9px', color: '#999' }}>
                {t('templates.preview_image')}
              </div>
              <div style={{ marginTop: '12px', paddingTop: '6px', borderTop: '1px solid #e0e0e0', fontSize: '8px', color: '#999', textAlign: 'center' }}>
                {editing.footer_text}
                {editing.company_name && ` · ${editing.company_name}`}
              </div>
            </div>
          </div>
        </div>

        {/* Save button */}
        <div className="flex justify-end mt-6 space-x-3">
          <button
            onClick={() => setEditing(null)}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50"
          >
            {t('common.cancel')}
          </button>
          <button
            onClick={handleSave}
            disabled={saving || !editing.name}
            className="px-6 py-2 text-sm font-semibold text-white bg-primary-600 hover:bg-primary-700 rounded-lg disabled:opacity-50 transition-colors"
          >
            {saving ? t('templates.saving') : t('templates.save')}
          </button>
        </div>
      </div>
    )
  }

  // ─── LIST VIEW ───
  if (loading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
      </div>
    )
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold text-gray-900">{t('templates.title')}</h1>
        <button
          onClick={handleNew}
          className="bg-primary-600 hover:bg-primary-700 text-white font-semibold py-2 px-4 rounded-lg transition-colors text-sm inline-flex items-center space-x-2"
        >
          <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
          <span>{t('templates.new')}</span>
        </button>
      </div>

      {error && (
        <div className="bg-red-50 text-red-700 px-4 py-3 rounded-lg mb-4">{error}</div>
      )}

      {templates.length === 0 ? (
        <div className="text-center py-20">
          <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
          </svg>
          <h3 className="mt-4 text-lg font-semibold text-gray-900">{t('templates.empty_title')}</h3>
          <p className="mt-1 text-sm text-gray-500">
            {t('templates.empty_subtitle')}
          </p>
          <button
            onClick={handleNew}
            className="mt-4 bg-primary-600 hover:bg-primary-700 text-white font-semibold py-2 px-4 rounded-lg text-sm"
          >
            {t('templates.create_first')}
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {templates.map((tpl) => (
            <div
              key={tpl.id}
              className="bg-white rounded-xl shadow-sm border border-gray-200 p-5 hover:shadow-md transition-shadow"
            >
              <div className="flex items-start justify-between mb-3">
                <div>
                  <h3 className="font-semibold text-gray-900">{tpl.name}</h3>
                  {tpl.company_name && (
                    <p className="text-xs text-gray-500 mt-0.5">{tpl.company_name}</p>
                  )}
                </div>
                <div className="flex items-center space-x-1">
                  <div className="w-4 h-4 rounded-full border border-gray-200" style={{ backgroundColor: tpl.primary_color }} />
                  <div className="w-4 h-4 rounded-full border border-gray-200" style={{ backgroundColor: tpl.secondary_color }} />
                </div>
              </div>

              {tpl.description && (
                <p className="text-sm text-gray-600 mb-3 line-clamp-2">{tpl.description}</p>
              )}

              <div className="flex flex-wrap gap-2 mb-3">
                {tpl.has_logo && (
                  <span className="inline-flex items-center text-xs bg-blue-50 text-blue-700 px-2 py-0.5 rounded-full">{t('templates.badge_logo')}</span>
                )}
                {tpl.has_base_pdf && (
                  <span className="inline-flex items-center text-xs bg-purple-50 text-purple-700 px-2 py-0.5 rounded-full">{t('templates.badge_pdf')}</span>
                )}
                {tpl.is_default && (
                  <span className="inline-flex items-center text-xs bg-green-50 text-green-700 px-2 py-0.5 rounded-full">{t('templates.badge_default')}</span>
                )}
              </div>

              <div className="flex items-center justify-end space-x-2 pt-2 border-t border-gray-100">
                <button
                  onClick={() => handleEdit(tpl)}
                  className="text-sm text-primary-600 hover:text-primary-800 font-medium"
                >
                  {t('common.edit')}
                </button>
                <button
                  onClick={() => handleDelete(tpl.id)}
                  className="text-sm text-red-600 hover:text-red-800 font-medium"
                >
                  {t('common.delete')}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
