"""Internationalization support for PDF reports and API responses.

Provides translation dictionaries for Catalan (ca), Spanish (es),
English (en), and Polish (pl). Used primarily in PDF report generation
to localize labels and static text.
"""

from typing import Literal

SupportedLocale = Literal["ca", "es", "en", "pl"]

SUPPORTED_LOCALES: list[SupportedLocale] = ["ca", "es", "en", "pl"]

DEFAULT_LOCALE: SupportedLocale = "ca"

# ---------------------------------------------------------------------------
# Translation dictionaries – keyed by locale, then by message key
# ---------------------------------------------------------------------------

_TRANSLATIONS: dict[str, dict[str, str]] = {
    # ── Catalan ──────────────────────────────────────────────────────────
    "ca": {
        # PDF report
        "pdf.title": "Informe",
        "pdf.dashboard_label": "Dashboard",
        "pdf.dashboard_uid": "Dashboard UID",
        "pdf.generated_at": "Generat el",
        "pdf.time_range": "Rang temporal",
        "pdf.panels_included": "Panells inclosos",
        "pdf.panels_section": "Panells del Dashboard",
        "pdf.image_not_available": "Imatge no disponible per al panell",
        "pdf.footer_default": "Generat per Grafana PDF Reporter",
        "pdf.page": "Pàgina",
        # Panel types
        "panel.graph": "Gràfic",
        "panel.timeseries": "Sèrie temporal",
        "panel.table": "Taula",
        "panel.stat": "Estadística",
        "panel.gauge": "Indicador",
        "panel.barchart": "Barres",
        "panel.piechart": "Circular",
        "panel.text": "Text",
        "panel.bargauge": "Barra indicador",
        "panel.heatmap": "Mapa de calor",
        "panel.geomap": "Mapa",
        # Report statuses
        "status.pending": "Pendent",
        "status.generating": "Generant",
        "status.completed": "Completat",
        "status.failed": "Error",
    },
    # ── Spanish ──────────────────────────────────────────────────────────
    "es": {
        "pdf.title": "Informe",
        "pdf.dashboard_label": "Dashboard",
        "pdf.dashboard_uid": "Dashboard UID",
        "pdf.generated_at": "Generado el",
        "pdf.time_range": "Rango temporal",
        "pdf.panels_included": "Paneles incluidos",
        "pdf.panels_section": "Paneles del Dashboard",
        "pdf.image_not_available": "Imagen no disponible para el panel",
        "pdf.footer_default": "Generado por Grafana PDF Reporter",
        "pdf.page": "Página",
        "panel.graph": "Gráfico",
        "panel.timeseries": "Serie temporal",
        "panel.table": "Tabla",
        "panel.stat": "Estadística",
        "panel.gauge": "Indicador",
        "panel.barchart": "Barras",
        "panel.piechart": "Circular",
        "panel.text": "Texto",
        "panel.bargauge": "Barra indicador",
        "panel.heatmap": "Mapa de calor",
        "panel.geomap": "Mapa",
        "status.pending": "Pendiente",
        "status.generating": "Generando",
        "status.completed": "Completado",
        "status.failed": "Error",
    },
    # ── English ──────────────────────────────────────────────────────────
    "en": {
        "pdf.title": "Report",
        "pdf.dashboard_label": "Dashboard",
        "pdf.dashboard_uid": "Dashboard UID",
        "pdf.generated_at": "Generated at",
        "pdf.time_range": "Time Range",
        "pdf.panels_included": "Panels Included",
        "pdf.panels_section": "Dashboard Panels",
        "pdf.image_not_available": "Image not available for panel",
        "pdf.footer_default": "Generated by Grafana PDF Reporter",
        "pdf.page": "Page",
        "panel.graph": "Graph",
        "panel.timeseries": "Time Series",
        "panel.table": "Table",
        "panel.stat": "Statistic",
        "panel.gauge": "Gauge",
        "panel.barchart": "Bar Chart",
        "panel.piechart": "Pie Chart",
        "panel.text": "Text",
        "panel.bargauge": "Bar Gauge",
        "panel.heatmap": "Heatmap",
        "panel.geomap": "Geomap",
        "status.pending": "Pending",
        "status.generating": "Generating",
        "status.completed": "Completed",
        "status.failed": "Failed",
    },
    # ── Polish ───────────────────────────────────────────────────────────
    "pl": {
        "pdf.title": "Raport",
        "pdf.dashboard_label": "Dashboard",
        "pdf.dashboard_uid": "Dashboard UID",
        "pdf.generated_at": "Wygenerowano",
        "pdf.time_range": "Zakres czasu",
        "pdf.panels_included": "Uwzględnione panele",
        "pdf.panels_section": "Panele Dashboardu",
        "pdf.image_not_available": "Obraz niedostępny dla panelu",
        "pdf.footer_default": "Wygenerowano przez Grafana PDF Reporter",
        "pdf.page": "Strona",
        "panel.graph": "Wykres",
        "panel.timeseries": "Seria czasowa",
        "panel.table": "Tabela",
        "panel.stat": "Statystyka",
        "panel.gauge": "Wskaźnik",
        "panel.barchart": "Wykres słupkowy",
        "panel.piechart": "Wykres kołowy",
        "panel.text": "Tekst",
        "panel.bargauge": "Wskaźnik słupkowy",
        "panel.heatmap": "Mapa ciepła",
        "panel.geomap": "Mapa",
        "status.pending": "Oczekujący",
        "status.generating": "Generowanie",
        "status.completed": "Ukończony",
        "status.failed": "Błąd",
    },
}


def get_translations(locale: str) -> dict[str, str]:
    """Return the full translation dictionary for *locale*.

    Falls back to ``DEFAULT_LOCALE`` if the requested locale is unknown.

    Args:
        locale: ISO 639-1 language code (e.g. ``"ca"``, ``"en"``).

    Returns:
        A mapping of translation keys to localised strings.
    """
    return _TRANSLATIONS.get(locale, _TRANSLATIONS[DEFAULT_LOCALE])


def t(key: str, locale: str = DEFAULT_LOCALE) -> str:
    """Translate a single message key.

    Args:
        key: Dot-separated translation key (e.g. ``"pdf.generated_at"``).
        locale: ISO 639-1 language code.

    Returns:
        Translated string, or the key itself if not found.
    """
    translations = get_translations(locale)
    return translations.get(key, key)


def get_locale_name(locale: str) -> str:
    """Return the human-readable name of a locale.

    Args:
        locale: ISO 639-1 language code.

    Returns:
        Locale display name.
    """
    names = {
        "ca": "Català",
        "es": "Español",
        "en": "English",
        "pl": "Polski",
    }
    return names.get(locale, locale)
